name: Sync from Overleaf

on:
  schedule:
    - cron: '*/15 * * * *'  # Check every 15 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Git
      run: |
        git config --global user.name "Overleaf Sync Bot"
        git config --global user.email "bot@github.com"
        
    - name: Clone Overleaf project
      run: |
        git clone ${{ secrets.OVERLEAF_GIT_URL }} overleaf-project
        
    - name: Copy files from Overleaf
      run: |
        # Remove old paper files
        rm -rf src/paper/*
        
        # Copy new files from Overleaf
        cp -r overleaf-project/* src/paper/
        
        # Clean up
        rm -rf overleaf-project
        
    - name: Check for changes
      id: changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git add src/paper/
        git commit -m "Sync from Overleaf: $(date)"
        git push
        
    - name: Trigger deployment
      if: steps.changes.outputs.changes == 'true'
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches" \
          -d '{"ref":"main"}'